# Site settings
title: Elevation Gain
header-img: img/home-bg.jpg
author: Mariano Dominguez
email: marianodominguez@gmail.com
copyright_name: ElevationGain
description: "Un blog sobre Trail Running, deportes de Montaña y vida al aire libre. Sky Running, Ultra Trail y todas las modalidades en el mundo del Trail."
baseurl:
url:
twitter_username: marian_dom
github_username:
facebook_username:  mariano.dom
email_username:  marianodominguez@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-69256555-1
google-site-verification: googlea28126ed35f99d48.html

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
